### ISSUE TITLE
Please upload netapp harvester code into this repository

### ISSUE THREAD

**Issue by gebi** [NetApp/Harvest#1]

**Comment by dutchiechris** [comment]
Sorry, Harvest is hosted internally at NetApp due to licensing constraints.  I have requested this repo to be removed.  Please post questions or suggested code updates [here](http://community.netapp.com/t5/OnCommand-Storage-Management-Software-Discussions/bd-p/oncommand-storage-management-software-discussions).

**Comment by gebi** [comment]
Hi @dutchiechris 

oh, that's a shame, i've made a direct integration for netapp harvester workers into systemd and wanted to make a PR. (this removes the flaky netapp-manager from the picture)
