### ISSUE TITLE
Flexgroup Read Latency

### ISSUE THREAD

**Issue by josepaulog** [NetApp/harvest#1123]
**Describe the bug**
Flexgroup read latency is incorrect.

**Environment**
ONTAP 9.10.1P3 , 
NABOX 3.1 (install method: OVA image)

**To Reproduce**
Create a FlexGroup on Netapp
Excute a workload (read/write operations)
Open NABOX to watch latencies
Open Dashboard: Harvest - cDOT / NetApp Detail: Volume - Details
Open the row : Volume WAFL Layer Drilldown
Look the panel: Read Latency
Metric: topk($TopResources, volume_read_latency{datacenter="$Datacenter",cluster="$Cluster",svm=~"$SVM",volume=~"$Volume"})

**Expected behavior**
Latencies similar to those obtained with the ONTAP CLI command "qos statistics volume latency show",  below 5ms.

**Actual behavior**
NABOX displays read latencies above 15ms.

**Possible solution, workaround, fix**
Looks like some metrics (volume_read_latency, volume_avg_latency) are incorrect for flexgroup volumes. and its constituents. It works fine for flexvols.

**Additional context**
Here is the output latencies from qos statistics volume latency show:

Workload            ID    Latency    Network    Cluster       Data       Disk    QoS Max    QoS Min      NVRAM      Cloud  FlexCache    SM Sync         VA     AVSCAN
--------------- ------ ---------- ---------- ---------- ---------- ---------- ---------- ---------- ---------- ---------- ---------- ---------- ---------- ----------
-total-              -   515.00us    65.00us   137.00us   302.00us        0ms        0ms        0ms    11.00us        0ms        0ms        0ms        0ms        0ms
-total-              -   512.00us    68.00us   132.00us   301.00us        0ms        0ms        0ms    11.00us        0ms        0ms        0ms        0ms        0ms
-total-              -   499.00us    61.00us   131.00us   296.00us        0ms        0ms        0ms    11.00us        0ms        0ms        0ms        0ms        0ms
-total-              -   521.00us    62.00us   132.00us   282.00us    34.00us        0ms        0ms    11.00us        0ms        0ms        0ms        0ms        0ms
-total-              -   501.00us    63.00us   130.00us   296.00us        0ms        0ms        0ms    12.00us        0ms        0ms        0ms        0ms        0ms
-total-              -   474.00us    61.00us   131.00us   271.00us        0ms        0ms        0ms    11.00us        0ms        0ms        0ms        0ms        0ms
-total-              -   492.00us    64.00us   132.00us   285.00us        0ms        0ms        0ms    11.00us        0ms        0ms        0ms        0ms        0ms
-total-              -   506.00us    72.00us   134.00us   289.00us        0ms        0ms        0ms    11.00us        0ms        0ms        0ms        0ms        0ms
-total-              -   465.00us    60.00us   127.00us   267.00us        0ms        0ms        0ms    11.00us        0ms        0ms        0ms        0ms        0ms
-total-              -   491.00us    65.00us   129.00us   286.00us        0ms        0ms        0ms    11.00us        0ms        0ms        0ms        0ms        0ms
-total-              -   474.00us    61.00us   131.00us   271.00us        0ms        0ms        0ms    11.00us        0ms        0ms        0ms        0ms        0ms
-total-              -   498.00us    61.00us   133.00us   293.00us        0ms        0ms        0ms    11.00us        0ms        0ms        0ms        0ms        0ms
-total-              -   514.00us    63.00us   132.00us   308.00us        0ms        0ms        0ms    11.00us        0ms        0ms        0ms        0ms        0ms

Thanks

**Comment by cgrinds** [comment]
hi @josepaulog what version of Harvest are you using? We made some fixes to how flex group latencies were calculated after the 22-05 releases.
#1055
#1060

If you're not using a Harvest release newer than 22-05, can you try that first? If you want to try these out, you can grab the latest [nightly build](https://github.com/NetApp/harvest/releases/tag/nightly).

**Comment by josepaulog** [comment]
Hi @cgrinds!

We are using NABOX 3.1 and it's running 22.02.0-4 (commit 9484df6):

root@nabox-harvest2:/netapp-harvest/bin# ./harvest -v
harvest version 22.02.0-4 (commit 9484df6) (build date 2022-02-15T09:11:03-0500) linux/amd64
root@nabox-harvest2:/netapp-harvest/bin#

I will update NABOX to the current version. I hope it solves the problem.

Thanks!

Thank you.

**Comment by cgrinds** [comment]
thanks @josepaulog make sure you try with the latest [nightly build](https://github.com/NetApp/harvest/releases/tag/nightly) since the fixes came after the `22.05` release.

**Comment by josepaulogomes** [comment]
Hi @cgrinds,

We did the update and it looks like the latency is now correct. We're still testing.

Thanks!

**Comment by josepaulog** [comment]
Hi @cgrinds,

We did the update and it looks like the latency is now correct. We're still testing.

Thanks!

**Comment by cgrinds** [comment]
Interesting! Can you share which version of Harvest you're using?

Sounds like support helped you grab archive files, which counter(s) were you using for the archive file comparison? Did you also capture latencies via the CLI during the same window? 

We're making a three way comparison:
1. latencies from performance ZAPI gathered by Harvest
2. latencies from ONTAP CLI
3. latencies from ONTAP archive files

All of these values come from the same ONTAP subsystem (counter manager) so they should match, but it sometimes is tricky to start/stop the measurements at the same time. When the measurements start effects the reported values since `latencies` require us to calculate the delta between two samples using a weighted average.

You can mitigate that by forcing each of the comparisons to use a similar interval of time. Since Harvest collects performance ZAPI data every 60s (`schedule data 60s` in `default.yaml`), when comparing with CLI commands you should use `-interval 60` or to smooth out some noise increase both to 5 minutes.

When we made the fixes mentioned up-thread, we validated that the ONTAP CLI command `statistics volume show -interval 60` matched the values Harvest reports.

**Comment by cgrinds** [comment]
awesome! we'll work on the list of things to grab and CLI commands to run. Will share with you once we've validated locally

**Comment by cgrinds** [comment]
Hi @josepaulog and @SergioSimao we dug into this more and have some updates.

1) It’s not an apples-to-apples comparison between volume `read_latency` and workload_volume `latency`. As this [KB article](https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/What_is_the_difference_in_latency_of_the_same_volume_between_statistics_volume_show_and_qos_statistics_volume_latency_show_commands) mentions, ONTAP returns slightly different latencies between `statistics volume show` and `qos statistics volume latency show`. That's true at the CLI and the ZAPI/REST APIs that Harvest uses.

You CLI was using `qos statistics volume latency` if you want similar values from Harvest, you need to enable the `workload_volume.yaml` template by uncommenting those lines in your `conf/zapiperf/default.yaml` file.

2) There was a bug in `zapiperf.go` that caused Harvest to calculate and store `read_latency` for some flex group constituents when normally we would ignore those constituent latencies because they failed to meet a minimum threshold of ops for that resource. This bug was not present in Harvest 1.6 and happened when porting the code to Harvest 2.

3) There was a bug in the `volume.go` plugin that caused the calculated weighted average to be slightly too low because the denominator, sum of read_ops for each constituent, was too high. This happened because Harvest used `read_ops` for constituents that failed to meet a minimum threshold. This bug also existed in 1.6.

The PR to address these issues is #1154. @rahulguptajss is working on documenting which ONTAP cli and ZAPI commands we used to validate these fixes.

**Comment by MrObvious** [comment]
The "qos statistics" output in the original post is not showing a line for that volume. There is no i/o on it, so that may be why.

What is the hostname/serial number? Do you have a perf archive during when this is being reviewed in Harvest? I could compare that way.

**Comment by josepaulog** [comment]
@MrObvious 

Cluster Serial Number: 180000011
Cluster Name:	SRJCPTINC13
Case Number: 2009223543

I think you can find the performance archive  and all collected data in the case.

**Comment by cgrinds** [comment]
Verified Harvest metrics match `qos statistics volume latency show`
Verified on `release/22.08.0` a05a0279

**Comment by cgrinds** [comment]
Leaving issue open while @josepaulog and @MrObvious continue their discussion

**Comment by cgrinds** [comment]
Thanks for sharing the log files @josepaulog - they were very helpful. We're improving how Harvest handles incomplete ONTAP counters and we'll ping you when they've made it through CI and integration tests.

**Comment by cgrinds** [comment]
Per https://github.com/NetApp/harvest/issues/1123#issuecomment-1215499917 closing
