### ISSUE TITLE
Harvest service doesn't work as expected

### ISSUE THREAD

**Issue by faguayot** [NetApp/harvest#122]
**Describe the bug**

When I started the service of harvest, it only runs two poller from 11 that we have defined in the harvest.yml. If I run the harvest process with the next command:  `**/opt/harvest/bin/harvest start**` or `**/opt/harvest/bin/harvest restart all the pollers**` run correctly. It happens the same with the different context defining for the service that is to say: _**start, restart, status and stop**_.

I attached an image of what we see in the beginning of the service

![image](https://user-images.githubusercontent.com/85484449/121025930-f6dad580-c7a5-11eb-8c29-7468da536fa1.png)

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Harvest version: harvest version 21.05.1-1 (commit 2211c00) (build date 2021-05-21T01:28:12+0530) linux/amd64
- Command line arguments used: [e.g. `bin/harvest start --config=foo.yml --collectors Zapi`]
- OS: RHEL 8.2
- Install method: yum
- ONTAP Version: 9.5 and 9.7 
- Other:

**To Reproduce**
Running the service systemctl start harvest.service

**Expected behavior**
It should run a process for every poller in my _harvest.yml_. 

**Actual behavior**
It only runs two pollers, sometimes none of them.

**Possible solution, workaround, fix**
Starting the gathering using the executable: "/opt/harvest/bin/harvest" instead of the service

**Comment by cgrinds** [comment]
i have a theory on what's going, but first a question.
* can you share the logs in `/var/log/harvest/` or check if there was anything logged for some of the pollers that didn't start?

One issue you hit is running `/opt/harvest/bin/harvest` as root.
When you do that, the pollers will write a pidfile in `/var/run/harvest/` owned by root.

Later when you try to start|stop|restart using `systemctl` the [Harvest service unit file](https://github.com/NetApp/harvest/blob/00eb06cfeaa9fea0e3862ef01153d9fe2a1069ff/service/harvest.service#L7) tells `systemctl` to use the `harvest` user. Since the pidfiles were created by root, the `harvest` user won't have permission to read or change those files.

To fix this (as root): 
* Stop the pollers
* `rm /var/run/harvest/*`
* `systemctl restart harvest`
* verify with `ps aux | grep polller` that the poller processes are owned by the `harvest` user
* verify that `ls -la /var/run/harvest` shows the pidfiles are owned by `harvest` 

As root, you could also su to `harvest` and then safely use `/opt/harvest/bin/harvest` directly too.

**Comment by faguayot** [comment]
Hello Chris,

I try to respond your questions:

- No, I didn't find anything in the /var/log/harvest related with my boot attempt. I found information relative to the service in the /var/log/messages.

![image](https://user-images.githubusercontent.com/85484449/121216407-26aadb80-c881-11eb-992c-867a3b0960dd.png)

- Yes, I've upgraded harvest version. Could be that a problem?
- Here I show you the output of `which harvest` and which harvest.yml files we have in our vm.
![image](https://user-images.githubusercontent.com/85484449/121220636-11d04700-c885-11eb-918a-310fa34122e3.png)


I was aware about the harvest user used in the service before I opened the issue and I tested the same that you said about stop the harvest manually and checking there aren't any poller process and the PID files in the /run/var/harvest too.

Here the results following your steps:

The permission for the /var/run/harvest:

![image](https://user-images.githubusercontent.com/85484449/121216910-9e790600-c881-11eb-9734-d7eb18e2ea47.png)

Without any poller process after stop the pollers with the command `harvest stop`:

![image](https://user-images.githubusercontent.com/85484449/121217135-d6804900-c881-11eb-89e7-f6817e224696.png)

The messages that appear after starting the service.
![image](https://user-images.githubusercontent.com/85484449/121216789-830dfb00-c881-11eb-8715-a6d845e47244.png)

The last test I did it was doing login into the vm with the harvest user and I tried to run with the command: `harvest start` without success.

![image](https://user-images.githubusercontent.com/85484449/121219675-3d9efd00-c884-11eb-87d4-6120b7607d5c.png)

**Comment by cgrinds** [comment]
Hi faguayot,

Thanks for the details and screenshots.

The fact that you have a harvest binary in `bin/harvest` implies you have multiple versions of harvest installed since the RPM does not install there. As you mentioned, I'm assuming this is from an earlier install. 

When using `systemctl`, the version of Harvest that will be used is the one in `/opt/harvest/`. That means `/etc/harvest/harvest.yml` will not be used. It would be less confusing to remove the old version of Harvest. Make sure there aren't any changes you want to keep and remove `/etc/harvest/`

Interesting that in your last example none of the pollers started. We're going in the wrong direction :)  Let's try starting just one poller in the foreground. Maybe there are errors that are being missed. 

Make a copy of your harvest.yml like so:
`cp /opt/harvest/harvest.yml /opt/harvest/one.yml`

Edit `/opt/harvest/one.yml` and remove or comment out all pollers but one.

Login or su as the `harvest` user
```
cd /opt/harvest/
bin/harvest --config one.yml --foreground
```

Hopefully you'll get some logging to the terminal that helps us figure out what's wrong.

**Comment by faguayot** [comment]
Hi Chris, 

Sorry but I think I have confused you because I forgot to show you the /bin/harvest is only a symbolic link which I created for recognize the command `harvest` in any path.

![image](https://user-images.githubusercontent.com/85484449/121309745-dbd1a800-c902-11eb-9ca2-41e3efa07c4b.png)

I remove the file /etc/harvest/harvest.yml and then I've tried to follow the steps for trying to start one poller in the foreground but it seems like my harvest doesn't recognize the flag `foreground`.

![image](https://user-images.githubusercontent.com/85484449/121309937-14718180-c903-11eb-95ab-a5d3943d0c32.png)

But I've deleted the foreground flag too and the result is the same without the error about the foreground.

![image](https://user-images.githubusercontent.com/85484449/121310746-f9534180-c903-11eb-9732-f4d31e393d52.png)


Thanks.
Best regards.

**Comment by cgrinds** [comment]
Yes, I left out the `start` command.
Can you try the following `bin/harvest start --config one.yml --foreground`

**Comment by faguayot** [comment]
Good point!
I had not realized, directly I copied the same command that you gave me. With the correct command runs. Below I attached the screenshot with the output.

![image](https://user-images.githubusercontent.com/85484449/121387684-2a0a9980-c94b-11eb-882f-1ff41345a923.png)

**Comment by cgrinds** [comment]
That's a good start! `SCES1P000` is running fine and that's one of the pollers that wasn't running earlier. What if you try running that same poller, but in the background like this: `bin/harvest start --config one.yml`

If you do that and then run the following, do you see the poller running?
`ps aux | grep poller`

What does the current log file for this poller show (see `/var/log/harvest/`) after trying to run in the background?

**Comment by faguayot** [comment]
With the poller `SCES1P000` in the background it works.

![image](https://user-images.githubusercontent.com/85484449/121487436-5fa69580-c9d2-11eb-88b4-bad3d0576774.png)

Yes, I see the poller which I launched:

![image](https://user-images.githubusercontent.com/85484449/121487833-c4fa8680-c9d2-11eb-9182-663320e72823.png)

This is the new traces in the log file for this poller:
![image](https://user-images.githubusercontent.com/85484449/121487974-e9566300-c9d2-11eb-984f-d4e27b1a2492.png)

**Comment by cgrinds** [comment]
More progress - options at this point:
 A. add a few more clusters to `one.yml` and confirm they work
 B. switch back to getting `systemctl` to work with your original `harvest.yml` If you want to try this, what if you change the `harvest.yml` that systemctl is going to use - the one in `/opt/harvest/harvest.yml`. Change it to include only cluster `SCES1P000`, since we know it works

With option B, make sure all pollers are stopped first, just so we're at a known state, then do the systemctl dance:
`systemctl restart harvest`
`ps aux | grep poller`

**Comment by faguayot** [comment]
I directly tried the init of the service and it run correctly. Below the evidences.

![image](https://user-images.githubusercontent.com/85484449/121660872-eb3c2700-caa3-11eb-813d-b9c9c57e246d.png)

**Comment by cgrinds** [comment]
Excellent! Looks like everything is working now.

**Comment by rahulguptajss** [comment]
@faguayot Pls close the issue if resolved.

**Comment by faguayot** [comment]
Thanks Chris.
The issue was resolved.
