### ISSUE TITLE
NetApp Overview cDot Dashboard

### ISSUE THREAD

**Issue by T1r0l** [NetApp/harvest#1311]
can you build this dashboard for harvest 2 also?
https://grafana.com/grafana/dashboards/10181-netapp-overview/

**Comment by cgrinds** [comment]
Thanks @T1r0l we'll take a look. We have plans to add a higher-level summary dashboard similar to this one.

**Comment by cgrinds** [comment]
Another example dashboard posted to Discord https://grafana.com/grafana/dashboards/14179-grafana-dashboard-for-netapp-ontap-v9-8/

**Comment by cgrinds** [comment]
Incorporate steps from https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/ONTAP_9_Performance_-_Resolution_Guide#s58720

**Comment by Hardikl** [comment]
The panels as per the link: https://grafana.com/grafana/dashboards/10181-netapp-overview/ are cluster level only. 
It shows 5 records (5 clusters) due to topk range selected.

This is the outlook of cDot dashboard when more clusters are present in datacenter.
topk selected as 5 but we have total 4 clusters in datacenter.
<img width="1736" alt="image" src="https://user-images.githubusercontent.com/83282894/202674312-3bfc43ae-8bd9-42ae-af02-98fafe073bea.png">

And yes, If we choose one cluster from cluster variable, then it would show that cluster's detail only
<img width="1751" alt="image" src="https://user-images.githubusercontent.com/83282894/202674670-e622fc58-0b87-44e9-9d2f-3a0d4bb28681.png">
