### ISSUE TITLE
svm is missing for one of the security_login_labels in Rest

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#1447]
security_login_labels{banner="Access restricted to authorized users ", cluster="umeng-aff300-01-02", datacenter="Rest", instance="localhost:12991", job="prometheus", scope="cluster", uuid="d3aa34d4-0580-11e8-bd9d-00a098d39e12"} 
-- | --
security_login_labels{banner="Access restricted to authorized users ", cluster="umeng-aff300-01-02", datacenter="Zapi", instance="localhost:12990", job="prometheus", **svm="umeng-aff300-01-02"**}

**Comment by Hardikl** [comment]
This is expected behaviour. 
In REST, security login can be `svm` scoped or `cluster` scoped. 
when it's svm scoped, svm label must be required.
While cluster scoped, only cluster label would be required, no svm will be returned from ONTAP.

<img width="875" alt="image" src="https://user-images.githubusercontent.com/83282894/201345370-fc592744-540a-4d3c-9db0-15b1526eb916.png">


<img width="1768" alt="image" src="https://user-images.githubusercontent.com/83282894/201345712-18c62f87-89a9-4188-816e-bc6a4499b798.png">

**Comment by Hardikl** [comment]
We don't have impact in dashboard. we have made the compatible query which can handle this `scope=cluster` in REST and `svm=cluster_name` in ZAPI.

we have queries like this way:
```
security_login_labels{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\", scope=\"cluster\", banner=\"\"} or security_login_labels{datacenter=~\"$Datacenter\", cluster=~\"$Cluster\", svm=~\"$Cluster\"} 
```
