### ISSUE TITLE
ONTAP: Volume Dashboard - Inodes usage

### ISSUE THREAD

**Issue by Falcon667** [NetApp/harvest#1535]
**Is your feature request related to a problem? Please describe.**
feature request. In the ONTAP: Volume dashboard a overview how many inodes are configured, used and percentage used.

**Describe the solution you'd like**
In the ONTAP: Volume dashboard a overview how many inodes are configured, used and percentage used..

**Additional context**
Since we have customers which are writing many small files, it would be visible how the indoes increased over time

**Comment by ruanruijuan** [comment]
![image](https://user-images.githubusercontent.com/83233519/203326297-bc80d154-54f4-4285-af91-e0c6bf6ac5bd.png)

**Comment by cgrinds** [comment]
hi @Falcon667 we'll take a look.

You probably already know this, but in case you don't, Harvest currently collects the counters you need
- `volume_inode_files_total`
- `volume_inode_files_used`

Your request is to include those in the Volume dashboard under an `Inodes usage` panel. Is that correct?

@ruanruijuan mentioned this EMS event may also be useful

```{
  "name": "wafl.vol.runningOutOfInodes",
  "severity": "error",
  "description": "This message occurs when the system detects that a volume is close to reaching its limit on the number of files that it can contain.",
  "corrective_action": "Consider using the \"volume modify <volume-name> -files <new-files-value>\" command to increase the number of files that the volume is allowed to contain. You can view the current value of the file threshold by using the \"volume show <volume-name> -fields files\" command.",
  "snmp_trap_type": "severity_based",
  "deprecated": false
}
```

**Comment by Falcon667** [comment]
Hi @cgrinds As always, your assumption is correct. An additional panel would make it easier to evaluate how much the inods have increased, e.g. in 30 days for a specific volume

**Comment by cgrinds** [comment]
Hi @Falcon667 pull request #1593 has the requested changes. To make this work also required a volume plugin change to calculate the percentage. I mention that because if you want to try these changes out, you'll need to grab nightly once this PR is reviewed and merged. 

In other words, if you use the included `volume.json` without the plugin, you will only see the `Inode Files Used` and `Inode Files Total` panels, but not the `Inode Files Used Percentage` panel.

Dashboard screenshot below. Does this work for you? Any changes, reordering, combining etc. you'd prefer?

![image](https://user-images.githubusercontent.com/242252/205729558-f4a22a4f-ab0f-491f-bc73-751e049bd0a9.png)
