### ISSUE TITLE
nabox certificate issue (SSL page)

### ISSUE THREAD

**Issue by ewilts** [NetApp/harvest#2107]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please let us know in a comment

### Problem

There's a wording issue on the SSL page.  The top box is private key, and the second box is labeled "certificate chain" but it's really the server cert.  The actual chain is the bottom box under root certificates.

There's also a typo on the description on the bottom box "Add you enterprise CA ".  "you" should be "your".
NAbox 3.3b2 (2023-03-30)

### Poller

n/a

### Version

3.3b2

### OS and platform

NAbox 3.3b2 (2023-03-30) - Alpine Linux 3.15.8

### ONTAP or StorageGRID version

n/a

**Comment by ybizeul** [comment]
You're totally right, the way it's implemented now expects the certificate only, but I don't think it should be.
In general, we want web servers to publish server certificate as well as any intermediate certificate, so I think the fix is on the API more than the typo on the page.
The bottom part is only to let Harvest success strict validation when connecting to systems with private CA, their are not use for the web service of NAbox.
I fixed the typo, thanks !

**Comment by ybizeul** [comment]
I was doing some tests and current behavior actually seems to be correct. The certificate chain has to be set in that field otherwise the intermediate certificate is missing and can’t be validated by the browser.

**Comment by cgrinds** [comment]
@ewilts is there a change you would like to see here or can we close this one?

**Comment by ybizeul** [comment]
@ewilts we can handle this on help@nabox.org
