### ISSUE TITLE
Volume Count mismatch

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#2657]
The volume count displayed on the datacenter dashboard doesn't match the count shown on SM landing page. The SM retrieves its count by calling the endpoint `/api/storage/volumes?return_timeout=120&is_object_store=true`. This task is to investigate the following two issues:

1. Are we correctly identifying root volumes? The REST API excludes root volumes, but it seems we might be marking additional volumes as root, resulting in the SM showing more volumes.

2. We need to include `is_object_store` in volume labels and adjust the count accordingly.

**Comment by Hardikl** [comment]
This is the detail about what `is_object_store` field and how it's being used/treated in volumes.

- This is same object store(**ONTAP S3**) where we used to create/update the object store in SVM and then attached it to local tier or cloud tier and access the buckets belongs to that object store based on the user permission.
- When we create object store in SVM either via running below CLI or via SM workflow, and later creating the buckets for them in SVM. 
<img width="685" alt="image" src="https://github.com/NetApp/harvest/assets/83282894/33ccead2-e880-4394-a7f6-933a4914c272">

- Each bucket would be associated with newly generated **flexgroup** volume (would contains metadata) and volume name starts with `fg_oss_xxx`.
- So, they are listed under the volumes category but they do not store the storage data same as other volumes, only holds object store related stuff.
- That's why SM do not show them in volumes page as it's not user created storage volume and any modification/deletion can't be possible by user until the bucket is existed in SVM.




**SM object store detail in 154 system**
<img width="1567" alt="image" src="https://github.com/NetApp/harvest/assets/83282894/556ad119-10ea-42a7-a3da-0d52d2ee540b">

**Harvest detail for those volumes** 
<img width="1774" alt="image" src="https://github.com/NetApp/harvest/assets/83282894/e9b52453-a2e7-49cc-b0d8-c14db931f4bb">




Reference KB link where those fg_oss_ volumes can't be deleted due to bucket: https://kb.netapp.com/onprem/ontap/da/S3/Cannot_delete_volume_%22because_this_volume_is_associated_with_object_store_bucket%22****

**Comment by Hardikl** [comment]
Detail about the volume counts

**Data for 154 system:**
- SM shows 204 volumes
- private cli shows 212 volumes, out of them 182 non-root volumes, 28 svm root volumes and 2 node root volumes
- public api shows 209 volumes, out of them 181 non-root volumes, 26 svm root volumes and 2 node root volumes

So, difference between 212 and 209 would be 
- 2 LS volumes(astra_302_m1, astra_30_m1) --> It's Load Sharing and may not be for storage data
- 1 TMP volume(moved_parent_temp__363098__415085__dummy) --> It's Temporary volume 

There are 5 object store volumes (starts with fg_oss_xxx). As explained above, they are listed but they are not for storage data.

**Conclusion:**
If we remove LS volumes, TMP volumes and Object store volumes from private or public api which gives exact 204 volumes which SM shows in volume grid.

**Comment by Hardikl** [comment]
As part of the fix, we will planning not to show LS, TMP type of volumes and object store volumes.

Potential places where this fix might be impacting dashboards.
- **Volume dashboard** which shows list of volumes but count --> No impact due to fix
- **Aggregate dashboard** which shows total volumes via `aggr_volume_count_flexvol` metric --> This would counted all the volumes including the constituents, but still count don't match. I will check further and update.
-- Need to check the name of this metric would be still valid ??


- **Snapmirror dashboard** which shows count of snapmirror and list of volumes protected --> 
-- Public api don't report LS relationships and private api reports them but without relationship_id. 
-- As `load sharing` relationships don't have `relationship_id`(below screenshot), They are already ignored now. 
-- So, No impact due to fix.
- **Datacenter dashboard**  which shows count of volumes --> This count will be updated and will show same SM.


This is snapmirror detail in cluster, where `rw` root volumes load shared to `ls` volumes.

<img width="1771" alt="image" src="https://github.com/NetApp/harvest/assets/83282894/3d69f963-a794-429f-bbc5-e37156416692">

**Comment by Hardikl** [comment]
So, This is the detail of `aggr_volume_count_flexvol` metric value.

**212** Total volumes in cluster: , 
**120** flexvols (including 1 temp volume) in `umeng_aff300_aggr2`
**80** flexvols in `test1`
**2** node volumes
**5** normal flexgroup 
**5** object store volumes (starts with fg_oss_xxx) 

Exploring the flexgroup constituents level detail,
**33** total constituents in `umeng_aff300_aggr2` 
**20** constituents from fg_oss_xxx flexgroups and 
**13** constituents from normal flexgroup

**13** total constituents in `test1`
**4** constituents from fg_oss_xxx flexgroups and 
**9** constituents from normal flexgroup



So, `umeng_aff300_aggr2` contains **120+33=153** volumes, whereas `test1` contains **80+13=93** volumes.
And our Harvest Aggregate dashboard would show the same volumes number

<img width="1718" alt="image" src="https://github.com/NetApp/harvest/assets/83282894/e1428dde-37c3-4601-a589-25718bb20bdb">


**Note:**
We should rename the metric name from `aggr_volume_count_flexvol` to `aggr_volume_count`.

**Comment by Hardikl** [comment]
Verified in 24.05 release branch at commit 74dcf38a872d2c38e633664314e0acc5b9f8d76b,

SM shows 273 volumes
<img width="1566" alt="image" src="https://github.com/NetApp/harvest/assets/83282894/12e1570e-c8f4-42aa-b846-c61d10ecc967">

Tested in both rest/zapi collector.
**For Rest:**
<img width="1785" alt="image" src="https://github.com/NetApp/harvest/assets/83282894/cdb66ee4-cb34-47cb-a009-98f875ddf10c">

<img width="1780" alt="image" src="https://github.com/NetApp/harvest/assets/83282894/4be760ad-f409-4c70-a3c1-f0cc12a12948">

**For Zapi:** it can show 2 extra volumes which are object store created and our docs stats the same.
<img width="1775" alt="image" src="https://github.com/NetApp/harvest/assets/83282894/dcd65d67-d61a-4de5-9acb-9842bf715055">

<img width="1776" alt="image" src="https://github.com/NetApp/harvest/assets/83282894/e3668b44-7e5f-4fa8-a85c-243759214e53">

<img width="1784" alt="image" src="https://github.com/NetApp/harvest/assets/83282894/576bbf33-dd52-480c-a6f0-e739aea5a7a3">
