### ISSUE TITLE
Issue with compute_metric plugin used for metric node_volume_total_data

### ISSUE THREAD

**Issue by munokar** [NetApp/harvest#2819]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please let us know in a comment

### Problem

We can see that dashboard panels using `node_volume_total_data` show "No data".
The metric `node_volume_total_data` is not reported by harvest only `node_volume_total_ops` is reported:

```
curl -s -X GET http://localhost:12993/metrics | grep -i node_volume_total
node_volume_total_ops{cluster="xxx33",datacenter="Prod",node="xx33n02"} 106.01722337150991
node_volume_total_ops{cluster="xxx33",datacenter="Prod",node="xx33n05"} 102.50109100253968
node_volume_total_ops{cluster="xxx33",datacenter="Prod",node="xx33n07"} 103.11766397719323
node_volume_total_ops{cluster="xxx33",datacenter="Prod",node="xx33n01"} 154.77648077249043
node_volume_total_ops{cluster="xxx33",datacenter="Prod",node="xx33n04"} 104.73408501885253
node_volume_total_ops{cluster="xxx33",datacenter="Prod",node="xx33n06"} 117.26551412532461
node_volume_total_ops{cluster="xxx33",datacenter="Prod",node="xx33n03"} 3382.4026900082085
node_volume_total_ops{cluster="xxx33",datacenter="Prod",node="xx33n08"} 121.16492158664705
```

The ZAPI config file contains the needed entries:

 ```
cat conf/zapiperf/cdot/9.8.0/volume.yaml

name:                     Volume
query:                    volume
object:                   volume

instance_key:             uuid

counters:
  - avg_latency
  - instance_name
  - ...
  - parent_aggr           => aggr
  - read_data
  - read_latency
  - read_ops
  - total_ops
  - vserver_name          => svm
  - write_data
  - write_latency
  - write_ops

plugins:
  - Aggregator:
    # plugin will create summary/average for each object
    # any names after the object names will be treated as label names that will be added to instances
    - node
  - Volume:
      include_constituents: false
  - MetricAgent:
      compute_metric:
        - total_data ADD read_data write_data
```

Looks like the compute_metric plugin is not working for some reason.

All the configuration YAML files are default from the RPM of ver 24.02.0-1.
There are no messages related to this issues in the poller log file.

Any advise how to troubleshoot this issue?

### Configuration

```text
./bin/harvest doctor
Admin:
    httpsd:
        listen: localhost:8887
Tools:
Exporters:
    prometheus:
        exporter: Prometheus
        local_http_addr: 127.0.0.1
        port_range: 12990-13050
        sort_labels: true
Defaults:
    collectors:
        - Zapi
        - ZapiPerf
    use_insecure_tls: true
    exporters:
        - prometheus
Pollers:
    unix:
        datacenter: local
        addr: -REDACTED-
        collectors:
            - Unix
        exporters:
            - prometheus
    xxx33:
        datacenter: Prod
        addr: -REDACTED-
        auth_style: basic_auth
        username: -REDACTED-
        password: -REDACTED-
        exporters:
            - prometheus
```

### Poller

xxx33

### Version

24.02.0-1

### OS and platform

Red Hat Enterprise Linux release 8.6 (Ootpa)

### ONTAP or StorageGRID version

NetApp Release 9.12.1P11

**Comment by cgrinds** [comment]
Thanks for the bug report @munokar. We discovered the same a couple of weeks ago and it is fixed in [nightly](https://github.com/NetApp/harvest/releases/tag/nightly).

The [changes](https://github.com/NetApp/harvest/pull/2786/files) are all in the template and dashboards which means you can apply them without taking a nightly, but taking the nightly is probably easier.

**Comment by munokar** [comment]
Thanks for the quick feedback.
Unfortunately I only searched for the full metric name ( `node_volume_total_data` ) so I didn't find the existing issue.

After updating the template file the to newest one it is working.
Interessting to see that the order of the elements in the list seems to make a difference since I could not identfy any other change in the template file.

**Comment by cgrinds** [comment]
No worries! Appreciate you opening the issue and glad it's working after updating. \o/

That's right, the plugin order matters. 

The order that plugins are listed in the template file is the order the plugins run. The earlier bug was caused by the `Aggregator` plugin running before the `compute_metric` one. That's a problem because the `compute_metric` plugin is only working on the volume metrics data, not the aggregated-by-node metrics data.

Changing the order means that the `compute_metric` plugin creates the `volume_total_data` metric before the Aggregator runs. That way the Aggregator will also aggregate `volume_total_data` and make it available at the by-node level as `node_volume_total_data`.

**Comment by munokar** [comment]
Thanks for the perfect explanation and the very quick response!
