### ISSUE TITLE
svm_vol_total_ops does not match SVM IOPS in SM

### ISSUE THREAD

**Issue by BrendonA667** [NetApp/harvest#2834]
### Problem

We see a discrepancy between the sum_vol_total_ops and the IOPS from the System Manager, which we can't explain
SM:
![grafik](https://github.com/NetApp/harvest/assets/99657787/5aa0b9e2-e6ef-4356-88f3-816d2f9fe5e8)

NABox Dashboard:
![grafik](https://github.com/NetApp/harvest/assets/99657787/3fadefc4-c287-420a-984f-4057f2fd6eff)

### Poller

-

### Version

23.11.0 and 24.02.0

### OS and platform

NABox

### ONTAP or StorageGRID version

ONTAP 9.11.1P8

**Comment by BrendonA667** [comment]
SM:
![grafik](https://github.com/NetApp/harvest/assets/99657787/341ab09a-95a9-4c5e-bb74-47c5571d3a78)

NABox:
![grafik](https://github.com/NetApp/harvest/assets/99657787/897e4c10-37eb-469a-8f14-7fc75d1c7918)

**Comment by Hardikl** [comment]
Hi @BrendonA667 ,
The 2 graphs which you have added above would not be directly comparable.
Because SM shows data at protocols level(protocols/nfs/services/{svm_uuid}) where you can choose protocol in dropdown, whereas in Harvest, we do show data at svm level(svm_vol_write_ops). 

SM screenshot where NFSv3 and iscsi options exist for this chosen svm.
<img width="992" alt="image" src="https://github.com/NetApp/harvest/assets/83282894/a4c83ee0-ad71-429b-ac53-929c11ee9789">

If you would like to compare exact values with SM, then you can compare the `iSCSI` panels and `NFS` panels for that svm in SVM dashboard, which would be almost similar.
<img width="1733" alt="image" src="https://github.com/NetApp/harvest/assets/83282894/aa971805-549a-4845-84c3-77b4e47fd80f">

**Comment by BrendonA667** [comment]
Hi @Hardikl thank you for your feedback.
Should not be the sum_vol_total_ops even higher then the value inside the SM? Question is because, we use QoS on the SVM level and we check over the SVM dashboard if we hit the limit. In that specific case we had a difference of almost 5000 IOPs

**Comment by Hardikl** [comment]
Thanks @BrendonA667 for the response.
 
Could you please provide few more details to get better understanding of this. 
1. As you shared earlier the SM screenshot, could you share the bigger size screenshot which contains the protocol name in it, so we can compare SM values at each protocol level(NFSv3, NFSv4(if it's applicable), Iscsi). 
2. Also, can you share the Harvest screenshot for the same protocols, meaning Iscsi panels, Nfsv3 panels and Nfsv4(if it's applicable) at the same time range for comparison.

Yes, we agreed that `svm_vol_total_ops` value should be almost equal or greater than all protocol level values. We are also evaluating as source of `svm_vol_total_ops` would be # of operations per second serviced by the volume level.

**Comment by BrendonA667** [comment]
Hi @Hardikl 

CIFS SM
![grafik](https://github.com/NetApp/harvest/assets/99657787/d7bbed82-632a-4932-bf0e-f7ca8d8de8cc)


CIFS Grafana
![grafik](https://github.com/NetApp/harvest/assets/99657787/9a048a9d-56d3-4d86-a6b6-75dfa37f9bb9)


NFSv3 SM
![grafik](https://github.com/NetApp/harvest/assets/99657787/db4a8bb1-0169-4c59-a2d0-63372978b8f1)

NFSv3 Grafana
![grafik](https://github.com/NetApp/harvest/assets/99657787/b78efdb6-7fdd-48c2-8ec7-08d04f6c3522)

**Comment by BrendonA667** [comment]
Hi @rahulguptajss apologize the delay.
About the protocol-level queries, with your queries the values are more or less the same.
Can you say why the SM has such higher spikes then ONTAP itself and Harvest?

**Comment by cgrinds** [comment]
Verified on 24.05.0 commit 6617960b using 10.195.15.41
