### ISSUE TITLE
Possibilty to add prefix for objects

### ISSUE THREAD

**Issue by BrendonA667** [NetApp/harvest#3329]
**Is your feature request related to a problem? Please describe.**
Feature request, which has the possibility to add a prefix for objects in a central place, so all objects which harvest collects use this. With that you can create a unique object fully Independent from other metrics in a database.

**Describe the solution you'd like**
Possibility to add a prefix in the conf file so that every object can use this, instead of creating custom files.

**Additional context**
We have one Prometheus instance which collects various of metrics like from the Harvest, Windows, Linux system etc. to make a metric unique as possible we created in the Harvest config dedicated custom files where we added the prefix netapp_ to the object.
<img width="607" alt="image" src="https://github.com/user-attachments/assets/d2eb4d06-a785-4ed0-b0e6-f6fc83a1467f">

**Comment by BrendonA667** [comment]
Hi @rahulguptajss my bad, I should read the documentation. I will test it in the next few days and give you feedback

**Comment by BrendonA667** [comment]
Hi @rahulguptajss we just deployed the harvest 24.11.1 version on our INT and used the global prefix setting. In general it works pretty well, but we see that for example shelf_psu_status does not have the defined prefix.

**Comment by BrendonA667** [comment]
Hi @rahulguptajss strange. On our side the setting looks like that. We will remove the underscore from the prefix to test it again
`Exporters:
  prometheus:                           #-> Choose Custom Name for Exporter
    exporter: Prometheus                #-> Set Exporter to be used (Harvest already comes with Prometheus Exporter)
    global_prefix: netapp_

Defaults:
  collectors:                           #-> Definition of default collectors (can also be set per poller)
     - Rest
     - RestPerf
  exporters:
     - prometheus
`

**Comment by cgrinds** [comment]
hi @BrendonA667 the suffixed global_prefix (`netapp_`) should work fine too. We have code that handles that. The prefixing happens right before the metrics are rendered, which is why it's odd that you are seeing a metric that is missing the prefix while the others have it.

If you curl the Prometheus exporter directly do you see the non-prefixed version or are you seeing these only in Prometheus?

Below are examples of querying the exporter directly:

```yaml
Exporters:
    prometheus1:
        exporter: Prometheus
        global_prefix: foople
```

I started a poller using the above exporter via `Defaults` like you did, let it run for 10 minutes, and then curled its `promPort`:

```bash
curl -s 'http://localhost:14001/metrics'
...
```

I confirmed that all metrics are `foople` prefixed with the following grep. This will only print metrics that aren't prefixed, and for me, this grep prints nothing:
```bash
curl -s 'http://localhost:14001/metrics' | sort | grep -Ev '^foople_'
```

```bash
curl -s 'http://localhost:14001/metrics' | sort | grep 'shelf_psu_status'
foople_shelf_psu_status{datacenter="dc-1",cluster="umeng-aff300-01-02",shelf="1.1",channel="",psu_id="1"} 1
foople_shelf_psu_status{datacenter="dc-1",cluster="umeng-aff300-01-02",shelf="1.1",channel="",psu_id="2"} 1
```

Can you share the output of running the same in your environment? Feel free to [email](mailto:ng-harvest-files@netapp.com) the result if you would rather.

**Comment by cgrinds** [comment]
Thanks for the follow up @BrendonA667. Glad you got it sorted out
