### ISSUE TITLE
Evaulate network xput 

### ISSUE THREAD

**Issue by cgrinds** [NetApp/harvest#339]
Mentioned on Slack by JOSE PEREZ 

I have a concern in regards to a couple of metrics from Harvest2.0. The network send throughput and node backend read throughput do not seem to coincide. The values seem off. Shouldn't they be roughly equal?

![image](https://user-images.githubusercontent.com/242252/126660718-11b8aeb3-6710-454d-b6a3-169b3a9a6315.png)

![image](https://user-images.githubusercontent.com/242252/126660751-0fa2b4e8-2a92-4487-a018-1e87db9974c0.png)

**Comment by cgrinds** [comment]
Compare with AIQ.UM

**Comment by cgrinds** [comment]
Are the correct units returned in perf zapi?

**Comment by vgratian** [comment]
I will ask the user for their ONTAP version. Node throughput and Network throughput might be slight off since the former can include other types of IOPs. However, in this case the difference is too large to be normal. A similar issue was reported in the past and it seemed like the issue was specific to ONTAP  9.7P4.

Other things that user can do: use their cluster CLI and compare it to the data from Harvest. 

Check throughput of Network interfaces:

```sh
cluster::> set -privilege diagnostic

Warning: These diagnostic commands are for use by NetApp personnel only.
Do you want to continue? {y|n}: y

cluster::*> statistics show-periodic -object nic_common -counter rx_bytes|tx_bytes|link_speed|link_up_to_downs -instance <nic> -interval 60 -node <node>
```
Check throughput of node:
```sh
cluster::*>  statistics show-periodic -object system:node -counter read_data|write_data -instance <node> -interval 60
```

**Comment by jperez08** [comment]
Current version is NetApp Release 9.7P4. 

I have used the suggested commands and harvest seems to be displaying the correct data.

**Comment by jperez08** [comment]
@vgratian Any other suggestions that may help resolve this issue?

**Comment by MrObvious** [comment]
I don't think this is an issue. https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/Active_IQ_Unified_Manager/Why_does_the_sum_of_all_volume_IOPs_in_an_aggregate_not_match_the_aggregate_IOPs%3F

**Comment by cgrinds** [comment]
Closing based on MrObvious last update. Please reopen if you still see this
