### ISSUE TITLE
7-mode template issues

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#423]
Pending 7mode issues.

**Cluster:**
health : missing information in zapi
disk busy: aggregator.go doesnt process global labels. Below warning
{"level":"warn","Poller":"7mode2","plugin":"ZapiPerf:Aggregator","caller":"goharvest2/cmd/poller/plugin/aggregator/aggregator.go:154","time":"2021-08-18T20:52:09+05:30","message":"label name for [node] missing, skipped"}

**disk:**
Missing "flash cache" and "flash pool" in dashboard
offline is not available in disk template

**Network:**
Missing FCP Send, FCP Receive, Transmission interrupts, Transmission errors, Link Down, Link Failure

**Network with Nvme/FC**
Missing FCP Send, FCP Receive, Nvme/FC Receive, Nvme/FC send, Transmission errors, Link Down, Link Failure
Need full dshboard check

**Aggregate:** Missing Mappings in 7 mode. Possible that 7 mode do not support these
1. Physical Space Used      
2. Capacity Tier Used           
3. Data Compaction space used   
4. space used for snapshot %  

**fcpport:**
{"level":"error","Poller":"7mode2","collector":"ZapiPerf:FcpPort","stack":[{"func":"New","line":"35","source":"errors.go"},{"func":"(*Fcp).Run","line":"29","source":"fcp.go"},{"func":"(*AbstractCollector).Start","line":"329","source":"collector.go"},{"func":"goexit","line":"1371","source":"asm_amd64.s"}],"error":"no metrics => read_data","caller":"goharvest2/cmd/poller/collector/collector.go:330","time":"2021-08-18T20:51:55+05:30","message":"plugin [Fcp]: "}

**volume**
{"level":"error","Poller":"v-7","collector":"Zapi:Volume","caller":"goharvest2/cmd/collectors/zapi/collector/zapi.go:320","time":"2021-08-25T13:49:30-04:00","message":"\u001b[31mmetric (volume-info.containing-aggregate) set value (tobago_2_aggr0): strconv.ParseUint: parsing \"tobago_2_aggr0\": invalid syntax\u001b[0m"}

**Comment by cgrinds** [comment]
See also 
- #415 
- #383

**Comment by Hardikl** [comment]
Above mentioned errors were solved.

found few errors:

11:44AM ERR goharvest2/cmd/collectors/zapi/collector/zapi.go:108 > Error importing subtemplate: copy_manager.yaml error="invalid indentation, line: 17" Poller=cluster-04 collector=ZapiPerf:CopyManager

11:44AM ERR goharvest2/cmd/collectors/zapi/collector/zapi.go:321 > metric (diagnosis-config-info.mon-version) set value (2.0): strconv.ParseUint: parsing "2.0": invalid syntax Poller=cluster-04 collector=Zapi:Status_7mode

./poller.go:472 > updated status, up collectors: 27 (of 28), up exporters: 1 (of 1) Poller=cluster-04

7mode and cmode network nvme/fc both are failing with ds_prometheous issue
![image](https://user-images.githubusercontent.com/83282894/135263981-76c6c5f9-f9aa-475e-8cee-877d86d46a8e.png)

poller_status in 7mode metadata dash shows wrong 
![image](https://user-images.githubusercontent.com/83282894/135265127-21865028-c299-45ce-b8e3-7f9c09d8f018.png)

do we need 2 metadata dashboards ?

do we need cluster and node variable for all 7mode dashboard ?

shall we remove duplicate dashboard from cmode ?

**Comment by Hardikl** [comment]
poller_status and other poller related metrics in metadata dashboard are reverse(0 means ok and 1 means error), but still grafana is showing green when it is actually healthy. No issue in reporting the right status.

![image](https://user-images.githubusercontent.com/83282894/135436664-0de5c6d2-50a1-4d40-896b-adebb5834019.png)

This is one of the rpm system(little old, but metadata dashboard is intact from july 26)
[root@scspb2435754004 H]# ps -aef |grep poller
root     23841 23226  0 15:40 pts/1    00:00:00 grep --color=auto poller
root     31240     1  0 Sep29 ?        00:00:32 bin/poller --poller unix --loglevel 2 --promPort 12990 --config ./harvest.yml --daemon
root     31280     1  0 Sep29 ?        00:06:10 bin/poller --poller cluster-03 --loglevel 2 --promPort 12991 --config ./harvest.yml --daemon
[root@scspb2435754004 H]# 

Only 2 clusters are up and pingable and we got pid for them, so only they show as Running. 

![image](https://user-images.githubusercontent.com/83282894/135436436-629f4ce7-44ac-4022-bda2-a7b0d8d0f19d.png)

In yesterday's docker testing, we got only one pid for unix and so it shows one running which is right. It seems we didn't get right ping value and pid in docker yesterday.

fix summary:
-> below both issue are fixed in #531 (1)
11:44AM ERR goharvest2/cmd/collectors/zapi/collector/zapi.go:108 > Error importing subtemplate: copy_manager.yaml error="invalid indentation, line: 17" Poller=cluster-04 collector=ZapiPerf:CopyManager

11:44AM ERR goharvest2/cmd/collectors/zapi/collector/zapi.go:321 > metric (diagnosis-config-info.mon-version) set value (2.0): strconv.ParseUint: parsing "2.0": invalid syntax Poller=cluster-04 collector=Zapi:Status_7mode

-> removal of metadata dashboard in 7mode and removal of cluster variable from all 7mode dashboards are done in #531  (2)

**Comment by rahulguptajss** [comment]
Can you verify poller ping status in docker once?

**Comment by cgrinds** [comment]
Poller ping should be fixed by https://github.com/NetApp/harvest/pull/530, which you may not have in your branch @Hardikl

**Comment by rahulguptajss** [comment]
Verified above errors. Noticed below.

1: Do we need lun dashboard for 7 mode?
2: Meta dashboard do not show 7 mode dashboard

**Comment by rahulguptajss** [comment]
meta dashboard is broken for cdot as well.

**Comment by cgrinds** [comment]
@rahulguptajss and I discussed - the meta dashboard was not showing data for him because unix poller was not running

**Comment by rahulguptajss** [comment]
Thanks moving to done now.
