### ISSUE TITLE
allow TLS server verification for basic auth

### ISSUE THREAD

**Issue by mamoep** [NetApp/harvest#51]
**Describe the bug**
Pollers won't start with this combination of options:
```
use_insecure_tls: false
auth_style: basic_auth
username: user
password: pass
```

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Harvest version: harvest version 21.05.1-1 (commit 2211c00) (build date 2021-05-21T01:28:12+0530) linux/amd64
- OS: RHEL 7.9
- Install method: yum
- ONTAP Version: 9.7P12

**To Reproduce**
Set use_insecure_tls to false and use basic authentication with username & password

**Expected behavior**
Pollers should start, server certifcate in ONTAP is valid.

**Actual behavior**
Pollers won't start.
```
2021/05/25 09:40:40  (warning) (poller) (hostname): init collector-object (Zapi:Node): connection error => invalid parameter => use_insecure_tls is false, but no certificates
2021/05/25 09:40:40  (warning) (poller) (hostname): aborting collector (Zapi)
2021/05/25 09:40:40  (warning) (poller) (hostname): init collector-object (ZapiPerf:SystemNode): connection error => invalid parameter => use_insecure_tls is false, but no certificates
2021/05/25 09:40:40  (warning) (poller) (hostname): aborting collector (ZapiPerf)
2021/05/25 09:40:40  (warning) (poller) (hostname): no collectors initialized, stopping
2021/05/25 09:40:40  (info   ) (poller) (hostname): cleaning up and stopping [pid=22027]
```

**Possible solution, workaround, fix**
Fix client.go logic to allow certificate verification with basic auth.

**Comment by sridevimm** [comment]
On a RHEL 7 system with fresh installation of harvest-21.06.0300-nightly.x86_64.rpm, Pollers started fine when "use_insecure_tls" was set to true. After checging it to false and restarted harvest, pollers don't start. 

IP: 10.193.114.246 (root/netapp)

[root@scspa2385980003 harvest]# bin/harvest status
Datacenter            Poller                PID        PromPort        Status              
+++++++++++++++++++++ +++++++++++++++++++++ ++++++++++ +++++++++++++++ ++++++++++++++++++++
umeng_aff300          umeng_aff300                                     not running         
F2240-127-26          F2240-127-26                                     not running         
+++++++++++++++++++++ +++++++++++++++++++++ ++++++++++ +++++++++++++++ ++++++++++++++++++++
[root@scspa2385980003 harvest]#

**Comment by rahulguptajss** [comment]
Both Ontap clusters do not have a valid certificate. Please see below error. You need to have a cluster with correct certificate to test this.

{"level":"warn","Poller":"umeng_aff300","time":"2021-06-05T18:41:23-04:00","message":"init collector-object (ZapiPerf:SystemNode): connection error => connection error => Post \"https://<<>>/servlets/netapp.servlets.admin.XMLrequest_filer\": x509: cannot validate certificate for <<>> because it doesn't contain any IP SANs"}
{"level":"warn","Poller":"umeng_aff300","time":"2021-06-05T18:41:23-04:00","message":"aborting collector (ZapiPerf)"}
{"level":"warn","Poller":"umeng_aff300","time":"2021-06-05T18:41:23-04:00","message":"no collectors initialized, stopping"}
{"level":"info","Poller":"umeng_aff300","time":"2021-06-05T18:41:23-04:00","message":"cleaning up and stopping [pid=4328]"}

**Comment by sridevimm** [comment]
Manageability and ONTAP teams are using clusters with self-signed certificates only. Due to the unavailability of cluster with purchased trusted certificate, this issue will be untested.

**Comment by mamoep** [comment]
You could import the CA of the self-signed certificates into the machine that hosts Harvest for testing. We are using a company-CA and it is basically the same thing.
