### ISSUE TITLE
Upgrade instructions for Docker installs

### ISSUE THREAD

**Issue by survive-wustl** [NetApp/harvest#652]
**Is your feature request related to a problem? Please describe.**

Upgrade instructions for Docker installs

**Describe the solution you'd like**

I have Harvest 21.08 installed & running using the Docker instructions. Now that 21.11 is out I want to update. How do I do that & keep my historic data?

**Describe alternatives you've considered**

**Additional context**

**Comment by rahulguptajss** [comment]
@survive-wustl Does this help?
https://github.com/NetApp/harvest/tree/main/docker#upgrade-harvest

**Comment by survive-wustl** [comment]
I have pulled a new image in but my pollers all have "v21.08.0" in their name. I think the name comes from harvest-compose.yml, can I rename them there, reconfigure the containers to eliminate the version info & retain my history?

I found this in a different part of the update instructions: 

After upgrade, you should re-import all dashboards (either grafana import cli or grafana UI) to get any new enhancements in dashboards.

Do I need to do that? If so how? 

My pollers are showing as stopped in the Metadata dashboard, but that might be related to this need to refresh.

-Will

**Comment by cgrinds** [comment]
hi @survive-wustl yes, the name doesn't match. We'll fix that, but the upgrade instructions are correct and you will be running `21.11` after pulling the new image. 

You can fix the name if you want by rerunning your [harvest generate](https://github.com/NetApp/harvest/tree/main/docker#config-and-using) command.

The re-import is not needed with docker compose because the dashboards are automatically imported.

**Comment by rahulguptajss** [comment]
Container name will be handled through issue #660

**Comment by cgrinds** [comment]
Closed by #660
