### ISSUE TITLE
Default nullPointMode to 'null as zero'

### ISSUE THREAD

**Issue by ybizeul** [NetApp/harvest#972]
**Is your feature request related to a problem? Please describe.**
On low-trafic volumes or entities, iterations might return zeroes often not considered for display in Grafana. In that case, we get graphs jumping around that makes it difficult to interpret. See screenshot below :
![image](https://user-images.githubusercontent.com/182035/163571250-0f3b9be7-9f90-4a01-a2d1-f98f2984d657.png)

**Describe the solution you'd like**
I think it most situations it is solved simply by setting `nullPointMode: null as zero` instead of `connected`. That's an option at the panel level in Grafana dashboards.

**Describe alternatives you've considered**
n/a

**Additional context**
This is how it looks like once changed :

![image](https://user-images.githubusercontent.com/182035/163571564-353bb218-1329-43ad-9755-5456dbe4f5be.png)

NAbox implements an option in Preferences to update `nullPointMode` in all dashboards.

**Comment by cgrinds** [comment]
hi @ybizeul - I think a better option may be to convert the `Graph (old)` panels to `Time series` panels. That's a change we've been making as we touch dashboards. 

There are lots of reasons to do the conversion and in most cases Grafana migrates the settings when you change the panel type in the UI. 

Can you try converting to Time series in your `Volume Top Average Latency` example above and let us know if that addresses your concern?

You may want to switch `Line interpolation` to Smooth instead of `Linear`. By default, the Time series panel uses `Never` for `Connect null values`.
![image](https://user-images.githubusercontent.com/242252/163807186-bc12e181-f76c-4dd0-805d-55ee351a0bc7.png)

**Comment by cgrinds** [comment]
Metrocluster dashboard updated #982

**Comment by cgrinds** [comment]
verified all panels were changed to timeseries
```sh
rg -F '"graph"' grafana/dashboards/7mode/ grafana/dashboards/cmode/
```
